import React from 'react';
import { hydrateRoot } from 'react-dom/client';
import './index.css';
import App from './App';
import reportWebVitals from './reportWebVitals';

// 1. default scaffold app (createRoot — for client-only rendering)
/*const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);*/

// 2. hydrateRoot — for hydrating server-generated HTML
//    ⚠️ Requires that the HTML in public/index.html already contains
//    the rendered output of <App /> (generated by the server).
//    hydrateRoot does NOT re-create the DOM — it attaches event handlers
//    to the EXISTING server-rendered HTML.
//
//    In a real app, the server would use renderToPipeableStream or
//    renderToReadableStream to generate the initial HTML.
//    With Create React App alone, this won't truly work because CRA
//    doesn't do server rendering — the <div id="root"></div> is empty.
//
//    To see it work: you'd need a server that renders <App /> to HTML
//    and injects it inside <div id="root">...server HTML here...</div>
const domNode = document.getElementById('root');
hydrateRoot(
    domNode,
    <React.StrictMode>
        <App />
    </React.StrictMode>
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();
